### PR TITLE
Drop unused blog

### PR DESCRIPTION
**Pull request by MTecknology**
The blog has been unused since inception. It's unlikely that this will change.

I think it would be best to drop the blog and (perhaps someday) bring it back if there's ever a need.

### CODE REVIEW

**Comment by MTecknology** [comment]
It appears rsnapshot really is dead technology. After over six months of not being reviewed, I am deleting my own clone. There's no point cluttering my own repositories for projects with maintainers that no longer care.

**Comment by MTecknology** [comment]
maintainer clearly doesn't care... it seems rsnapshot truly is dead

**Comment by MTecknology** [comment]
@sgpinkus Should this be re-opened?

**Comment by sgpinkus** [comment]
Yes. Happy to drop the blog. I'll approve if you reopen (CC @djk20).

**Comment by sgpinkus** [comment]
Done.

**Pull request closed without merging**
