### PR TITLE
Remove duplicate download options

### PR DESCRIPTION
**Pull request by MTecknology**
The first portion of the download page mentions that the package is already available in [their] distro of choice. This will be true almost all of the time (this is a great and stable tool). It's will most likely also be the best way to install it since the package will account for variations in the different distros.

The next bit goes on to mention two places where source builds can be found (github releases & web downloads). Having copies of these files on rsnapshot.org provides slightly better aesthetics, however the people interested in this download option aren't likely to care. I suspect the majority of people interested will be package maintainers who will download it from github anyway.

A down side to the rsnapshot.org approach is that this repository has a lot of binary blobs, which is something that git (and VCS in general) isn't really suited for. In this case, the repository would only be about 400KB without the release files. Instead, it's already about 17MB. This is over 4x the size of the main rsnapshot repository.

In my opinion, it makes the most sense to move those files to github releases (as attached files) and drop them from this repository (& subsequently rsnapshot.org). This would provide a few other benefits as well, without decreasing accessibility to downloads.

### CODE REVIEW

**Comment by MTecknology** [comment]
It appears rsnapshot really is dead technology. After over six months of not being reviewed, I am deleting my own clone. There's no point cluttering my own repositories for projects with maintainers that no longer care.

**Comment by MTecknology** [comment]
maintainer clearly doesn't care... it seems rsnapshot truly is dead

**Comment by MTecknology** [comment]
@sgpinkus Should this be re-opened?

**Comment by sgpinkus** [comment]
> In my opinion, it makes the most sense to move those files to github releases (as attached files) and drop them from this repository (& subsequently rsnapshot.org). This would provide a few other benefits as well, without decreasing accessibility to download

Agree Github releases should be the single source, don't think anyone will have an issue with that. PITA maintaining copies in two places. The tar.gz archinve aren't very useful over `git clone` anyway. I believe the downloads page is there only for historical record as really old tar archives aren't available on Github. That just need to be made more clear on the downloads page:  pre 1.4.0 -> downloads. Moving forwards -> github. I think we can delete the 1.4.x versions listed there too.

I don't think this PR is quite right though: Should be update the text to point to Github for 1.4.0 on, delete the 1.4.x archives.

**Pull request closed without merging**
